LAKE_AND_RIVERS = {
    'бася': 'basya-hilkovichi',
    'березина_березино': 'berezina-berezino',
    'березина_борисов': 'berezina-borisov',
    'березина_бобруйск': 'berezina-bobruysk',
    'березина_светлогорск': 'berezina-svetlogorsk',
    'беседь': 'besed-svetilovichi',
    'бобр': 'bobr-kuty',
    'брагинка': 'braginka-rudnya_zhuravleva',
    'вилейское водохранилище': 'vileyskoe-vileyka',
    'вилия_малые_свирянки': 'viliya-m_sviryanki',
    'вилия_вилейка': 'vilia-vileyka',
    'вилия_стешицы': 'vilia-steshicy',
    'вилия_михалишки': 'viliya-mihalishki',
    'вихра': 'uroven-vody-v-reke-vihra-g-mstislavl',
    'гавья': 'gavia-lubinyata',
    'горынь': 'gavia-lubinyata',
    'дисна': 'disna-sharkovshina',
    'днепр_болшево': 'dnepr-bolshevo',
    'днепр_дорогобуж': 'dnepr-dorogobuzh',
    'днепр_соловьево': 'dnepr-solovevo',
    'днепр_смоленск': 'dnepr-smolensk',
    'днепр_орша': 'dnepr-orsha',
    'днепр_могилев': 'dnepr-mogilev',
    'днепр_жлобин': 'dnepr-zhlobin',
    'днепр_речица': 'dnepr-rechica',
    'днепр_лоев': 'dnepr-loev',
    'добысна': 'dobysna-mrudnya',
    'друть_городище': 'drut-gorodishe',
    'друть_чигирская_ГЭС': 'drut-chigirinskaya_ges',
    'дрыса': 'drysa-dernovichi',
    'заславское_водохранилище': 'zaslavskoe',
    'ивня-бонда': 'ivnya-bonda-budka',
    'ипуть_крутояр': 'iput-krutoyar',
    'ипуть_ущерпье': 'iput-usherpe',
    'ипуть_добруш': 'iput-dobrush',
    'канал_бычок': 'bychok-ozerany',
    'котра': 'kotra-sahkombinat',
    'краснослободское водохранилище': 'kransoslobodskoe-vodohranilishe-nrozhan',
    'кривинка': 'krivinka-dobrygory',
    'лань': 'lan-mokrovo',
    'лесная_тюхиничи': 'lesnaya-tuhinichi',
    'лесная_каменец': 'lesnaya-kamenec',
    'мухавец': 'muhavec-brest',
    'нарев': 'narev-nemerzha',
    'нарочь': 'reka-naroch-naroch',
    'нача': 'nacha',
    'неслуха': 'nesluha-rudsk',
    'оболь': 'obol',
    'озеро дривяты': 'drivyaty-braslav',
    'озеро лукомское': 'lukomskoe-novolukoml',
    'озеро нарочь': 'naroch',
    'озеро червоное': 'chervonoe',
    'ольшанка': 'olshanka-bogdanovo',
    'ореса': 'oressa-andreevka',
    'остер': 'oster-hodun',
    'ошмянка': 'oshmyanka-byacini',
    'пина': 'pina-pinsk',
    'полота': 'polota-yankovo',
    'припять_пинск': 'pinsk',
    'припять_черничи': 'pripyat-chernichi',
    'припять_петриков': 'pripyat-petrikov',
    'припять_мозырь': 'pripyat-mozyr',
    'припять_наровля': 'pripyat-narovlya',
    'проня': 'pronya-mihailov',
    'проня_приток_сожа': 'uroven-vody-v-reke-pronya-d-letyagi-segodnya',
    'птичь_дараганово': 'ptich-daraganovo',
    'птичь_первая_слободка': 'ptich-1slobodka',
    'россь': 'ross-studenec',
    'свислочь_хмелевка': 'svisloch-hmelevka',
    'свислочь_теребуты': 'svisloch-terebutyi',
    'свислочь_диневичи': '74163',
    'случь_ленин': 'sluch-lenin',
    'случь_клепчаны': 'sluch-klepchany',
    'сож_ускосы': 'sozh-uskosy',
    'сож_кричев': 'uroven-vody-v-reke-sozh-g-krichev-segodnya',
    'сож_славгород': 'uroven-vody-v-reke-sozh-g-slavgorod',
    'сож_гомель': 'sozh-gomel',
    'солигорское водохранилище': 'soligorsk',
    'ствига': 'stviga-korotichi',
    'страча': 'stracha-olhovka',
    'стыр': 'styr-lopatino',
    'сушанка': 'sushanka-susha',
    'уборть': 'ubort-krasnobereje',
    'уза (приток сожа)': 'uza-pribor',
    'узлянка': 'uzlyanka-uzla',
    'улла': 'ulla-bocheikovo',
    'усвяча': 'usvyacha-novoselki',
    'цна (приток припяти)': 'cna-dyatlovichi',
    'чигиринское водохранилище': 'chigirinskoe-ges',
    'щара': 'shara-slonim',
    'ясельда_береза': 'yaselda-bereza',
    'ясельда_сенин': 'yaselda-senin',
}
