version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  web:
    image: denisktv/web:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  
  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - static_value:/var/html/static
    command: certonly --webroot --webroot-path=/var/html/static --email deniskforwork@gmail.com --agree-tos --no-eff-email -d fisherjournal.xyz --renew-by-default

volumes:
  static_value:
  media_value:
  db_value:
  letsencrypt:
